---
title: "Mapa de temperatura superficial de la tierra (LST) en infraestructura gris de la Gran Área Metropolitana"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leaflet.extras)
library(leaflet.opacity)
library(leafem)
library(esri2sf)
library(raster)

#--------------- URL de geoservicios --------------

url_agfs_limite_gam <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_gam/FeatureServer/0"

url_raster_lst <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos-calentamiento-urbano/master/gam/LST_INFRAESTRUCTURA_GRIS_GAM_WEB.TIF"

#--------------- Objetos sf y raster ---------------

# Límite de la GAM
sf_limite_gam <-
  esri2sf(url_agfs_limite_gam)

# Límite de la GAM (reproyectado a Web Mercator)
sf_limite_gam_web <- 
  sf_limite_gam %>%
  st_transform(3857)

# Capa raster de LST (en Web Mercator)
raster_lst_infraestructura_gris <-
  raster(url_raster_lst) %>%
  crop(sf_limite_gam_web) %>%
  mask(sf_limite_gam_web)

raster_lst_infraestructura_gris[raster_lst_infraestructura_gris==65535] <- NA
min_raster_lst_infraestructura_gris <- format(cellStats(raster_lst_infraestructura_gris, stat='min'), digits=3, nsmall=1)
max_raster_lst_infraestructura_gris <- format(cellStats(raster_lst_infraestructura_gris, stat='max'), digits=3, nsmall=1)
mean_raster_lst_infraestructura_gris <- format(cellStats(raster_lst_infraestructura_gris, stat='mean'), digits=3, nsmall=1)

#---------------- Paletas de colores ---------------

# LST
colores_lst <- c("green", "yellow", "red")
pal_lst <- 
  colorNumeric(
    colores_lst, 
    values(raster_lst_infraestructura_gris),
    na.color = "transparent"
  )

```

Row {data-height=800}
-----------------------------------------------------------------------

### 

```{r}

leaflet() %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_gam,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite de la GAM"
  ) %>%
  addRasterImage(
    raster_lst_infraestructura_gris, 
    layerId = "raster",    
    colors = pal_lst,
    opacity = 0.9,
    group = "LST"
  ) %>%  
  addLegend(
    title = "LST (°C)",
    values = values(raster_lst_infraestructura_gris),
    pal = pal_lst,
    position = "bottomright",
    group = "LST"
  ) %>%    
  addLayersControl(
    baseGroups = c("CartoDB Dark Matter", "OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI"),
    overlayGroups = c("Límite de la GAM", "LST"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$CartoDB.DarkMatter
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates() %>%
  addSearchOSM() %>%
  addResetMapButton() %>%
  addOpacitySlider(layerId = "raster")
```

Row {data-height=200}
-----------------------------------------------------------------------

### Temperatura mínima {.value-box} {data-width=333}
```{r}
valueBox(
  value = "LST mínima", 
  caption = paste("<h2><strong>", min_raster_lst_infraestructura_gris,  "°C</strong></h2>")
)
```

### Temperatura máxima {.value-box} {data-width=333}
```{r}
valueBox(
  value = "LST máxima", 
  caption = paste("<h2><strong>", max_raster_lst_infraestructura_gris,  "°C</strong></h2>")
)
```

### Temperatura promedio {.value-box} {data-width=333}
```{r}
valueBox(
  value = "LST promedio", 
  caption = paste("<h2><strong>", mean_raster_lst_infraestructura_gris,  "°C</strong></h2>")
)
```
